[package]
name = "mqtt-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.7.2", default-features = false }
futures = "0.3.31"
serde = "1.0.219"
tokio = { version = "1.40.0", default-features = false } 
tokio-rustls = "0.26.1"

[features]
bitpack = []
