[package]
name = "mqtt-client"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
mqtt-core = { path = "../mqtt-core" }
bytes = "1.8.0"
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.31"
tokio-rustls = "0.26.1"

[dev-dependencies]
